### ISSUE TITLE
Reduce number of transitive dependencies loaded 

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/go-fsimpl#14]
A downside of this module is the number of transitive dependencies pulled in can get quite high (due to supporting so many different filesystems). This can cause significant bloat.

I've gotten a few pieces of early feedback from people who might find this useful, but want to avoid all of the transitive dependencies this pulls in. This is absolutely fair - I want to strike a balance between being usable and reasonably lean.

One way to reduce unwanted bloat could involve splitting each FS implementation into its own sub-package, and then in Go 1.17 this would take advantage of the new [lazy module loading](https://github.com/golang/go/issues/36460) work.

Splitting packages would only be a help to individually-targeted filesystems (like, say, if you _knew_ you wanted a `GitFS`), because `LookupFS` would still need to be able to choose the correct implementation for the given scheme.

One way around this could be to alter the API such that `LookupFS` only chooses from an explicitly-registered set of implementations, like:

```go
mux := fsimpl.NewMux()
mux.Add(blobfs.New)
mux.Add(gitfs.New)

fs, err := mux.Lookup(url)
```

(adapted from [a conversation in Gophers Slack](https://gophers.slack.com/archives/C02A3DRK6/p1620062312185600))

This feels to me like something that should be solved well before v1, and probably even before the first v0 release, since it completely breaks API.

**Comment by hairyhenderson** [comment]
I've labeled this as `help wanted` since I'm looking for more feedback on what a good balance between being simple to use and reducing the number of dependencies that need to be pulled in.

However, I'll probably experiment with some approaches before closing this, and before a lot of feedback comes in 😉

**Comment by gen2brain** [comment]
Something like `image.RegisterFormat` would be nice, instead of a magic string, it can use a URL scheme. So `LookupFS` will work only with sub-packages imported with `_`.

**Comment by hairyhenderson** [comment]
Thanks for the feedback @gen2brain. In general I'm not a huge fan of requiring anonymous imports, as they can tend to be a bit too "magical" from a usability perspective.

Also, this means that each package would then need an `init()` function that registers the FS with some central registry. I'm not sure I fully understand the technicalities, but @bcmills cautioned against that [in Slack](https://gophers.slack.com/archives/C02A3DRK6/p1620062236184100) yesterday:

> Honestly, I would avoid the `import`-based `LookupFS` function if you can. The registration hooks for that function will pretty much destroy the linker's ability to prune out unused implementations.

A more explicit approach (as outlined in the description) would also mean that no `init()` functions are necessary, and no global registry is necessary either.

However, I'm open to arguments either way.

Right now we won't see an immediate benefit from any of this, but the goal is that with Go 1.17 (~August 2021) this should be much more efficient to use.

**Comment by bcmills** [comment]
One major downside of registration functions is that they prevent the linker from pruning out otherwise-irrelevant functions: if something is reachable via a global registration, then the linker can't eliminate it even if it isn't actually used.

Another downside is that the program ends up paying the (small but nonzero) cost of `init`-time initialization even if it doesn't end up executing the code path that would actually need to look up the filesystem.

A third is that, especially for a URL-based `Lookup` function, implicit registration implies that you have to think about (and possibly resolve) duplicate or overlapping registrations, which likely implies either init-time `panic`s (and more difficult refactoring if an implementation is moved), or some kind of init-order-dependent resolution (which makes the code much more subtle and harder to reason about).

In contrast, with an explicit user-configured multiplexer, the user can control the order of registration and can resolve collisions explicitly in their own code.

**Comment by hairyhenderson** [comment]
Some early results from splitting into packages are in #15 - tl;dr: 93% reduction in binary size when only using the `filefs` package.

TBH I'm a bit confused as this is with Go 1.16, without the Go 1.17 enhancements. But I'll take it!

**Comment by hairyhenderson** [comment]
Now that this is using Go 1.17, and since #15 has been merged for a while, I think the transitive deps are as low as they're gonna get. At least, as far as I can tell 😉. So, I'll close this now.
